config/routes.rb
EaLunchReservation::Application.routes.draw do
  root :to => "reservations#index"
  resources :reservations, except: :show do
    member do
      put :backup_availability
    end
  end
  resource :update, only: [:show]
  resources :foods, only: []
  resources :users, only: []
  resource :summaries, only: [] do
    get :today
    get :query
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :backup_dish_ids, :dish_ids, :comment, :food_only, :use_backup

  has_and_belongs_to_many :backup_dishes, association_foreign_key: :backup_dish_id, join_table: 'reservations_backup_dishes', class_name: Food
  has_and_belongs_to_many :dishes, association_foreign_key: :dish_id, join_table: 'reservations_dishes', class_name: Food
  validates :user_id, :dish_ids, presence: true
  validates_length_of :comment, maximum: 200, allow_blank: true
  validate :eligibility_to_reserve, on: :create

  before_save :set_price
  before_update :eligibility_to_update_reservation
  after_save :update_today_summary
  after_destroy :update_today_summary

  scope :food_only, where(food_only: true)

  BASIC_PRICE = 4000
  DEADLINE = 11.hour + 40.minute

  def self.today
    where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  def self.deadline
    Time.zone.now.beginning_of_day + DEADLINE
  end

  private
  def set_price
    self.price = dishes.map(&:price).sum unless dish_ids.empty?
    self.price += BASIC_PRICE unless food_only?
  end

  def eligibility_to_reserve
    if Reservation.today.exists?(user_id: user_id)
      self.errors[:user_id] << 'You already reserved for today. Please come back by tomorrow!'
    end
  end

  def eligibility_to_update_reservation
    eligibility_to_reserve if user_id_changed?
  end

  def update_today_summary
    Summary.update_today_summary
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :collect_foods, only: [:index, :new, :edit, :create, :update]
  before_filter :collect_users, only: [:new, :edit, :create, :update]
  before_filter :normalize_params, only: [:create]
  before_filter :preload_reservation, only: [:edit, :update]
  before_filter :find_reservation, only: [:backup_availability]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.today.joins(:user).includes(:dishes, :backup_dishes).order('reservations.created_at')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        session[:last_user] = @reservation.user_id
        format.html { redirect_to reservations_path, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to reservations_path, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end

  def backup_availability
    respond_to do |format|
      if @reservation.update_column(:use_backup, params[:reservation][:use_backup])
        format.json { head :no_content }
      else
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def collect_foods
    @foods = Food.available.order('name').select('name, id')
  end

  def collect_users
    @users = User.not_reserved.order('name')
  end

  def preload_reservation
    find_reservation
    @users += [@reservation.user] if @users
  end

  def find_reservation
    @reservation = Reservation.find(params[:id])
  end

  def normalize_params
    params[:reservation][:comment] = params[:reservation][:comment][0..199] if params[:reservation][:comment].present?
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def dishes_selection_input(type, builder)
    builder.input("#{type}_ids", label_method: :name, value_method: :id, collection: @foods, label: type.to_s.pluralize.humanize, input_html: { multiple: true, class: 'chzn-select span6' })
  end

  def user_selection_input(builder, reservation)
    builder.input(:user_id, label_method: :name, value_method: :id, collection: @users, label: 'User', prompt: 'Select user', selected: reservation.try(:user_id) || session[:last_user], input_html: { class: 'chzn-select span3' })
  end
end

app/views/reservations/_form.html.haml
= simple_form_for(@reservation) do |f|
  = f.error_notification

  .form-inputs
    = user_selection_input(f, @reservation)
  .form-inputs
    = dishes_selection_input(:dish, f)
  .form-inputs
    = dishes_selection_input(:backup_dish, f)
  .form-inputs
    = f.input :comment, as: :text, input_html: { rows: 5 }
  .form-inputs
    = f.input :food_only, as: :radio_buttons
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/reservations/_list.html.haml
%table.table.table-bordered.table-hover
  %tr
    %th User
    %th Dishes
    %th Backup dishes
    %th Backup in use?
    %th Price
    %th Updated at
    %th Comment
    %th Food only?
  - @reservations.each do |reservation|
    %tr
      %td= reservation.user.name
      %td= reservation.dishes.map(&:name).join(', ')
      %td= reservation.backup_dishes.map(&:name).join(', ')
      %td
        = form_for reservation, remote: true, url: backup_availability_reservation_path(reservation)  do |f|
          = f.check_box :use_backup
      %td= reservation.price
      %td= reservation.updated_at.in_time_zone.strftime '%b-%d-%H:%M'
      %td= reservation.comment
      %td= reservation.food_only

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'
= button_to 'Back', reservations_path, method: :get, class: 'btn btn-warning'

app/views/reservations/index.html.haml
%h1 Listing reservations
= button_to 'New Reservation', new_reservation_path, class: 'btn btn-primary', method: :get

%table.table.table-bordered.table-hover
  %tr
    %th User
    %th Dishes
    %th Backup dishes
    %th Backup in use?
    %th Price
    %th Updated at
    %th Comment
    %th Food only?
    %th
    %th
  - @reservations.each do |reservation|
    %tr
      %td= reservation.user.name
      %td= reservation.dishes.map(&:name).join(', ')
      %td= reservation.backup_dishes.map(&:name).join(', ')
      %td
        = form_for reservation, remote: true, url: backup_availability_reservation_path(reservation)  do |f|
          = f.check_box :use_backup
      %td= reservation.price
      %td= reservation.updated_at.in_time_zone.strftime '%b-%d-%H:%M'
      %td= reservation.comment
      %td= reservation.food_only
      %td= link_to 'Edit', edit_reservation_path(reservation)
      %td= link_to 'Destroy', reservation, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br
= button_to 'New Reservation', new_reservation_path, class: 'btn btn-primary', method: :get

app/views/reservations/new.html.haml
%h1 New reservation

= render 'form'
= button_to 'Back', reservations_path, method: :get, class: 'btn btn-warning'

app/views/reservations/show.html.haml
%p#notice= notice

%p
  %b User:
  = @reservation.user

= link_to 'Edit', edit_reservation_path(@reservation)
\|
= link_to 'Back', reservations_path