config/routes.rb
EaLunchReservation::Application.routes.draw do
  root :to => "reservations#index"
  resources :reservations, except: :show do
    member do
      put :backup_availability
    end
  end
  resource :update, only: [:show]
  resources :foods, only: []
  resources :users, only: []
  resource :summaries, only: [] do
    get :today
    get :query
  end
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :price, :available
  scope :available, where(available: true)
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.haml
= simple_form_for(@food) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :price

  .form-actions
    = f.button :submit

app/views/foods/edit.html.haml
%h1 Editing food

= render 'form'

= link_to 'Show', @food
\|
= link_to 'Back', foods_path

app/views/foods/index.html.haml
%h1 Listing foods

%table
  %tr
    %th Name
    %th Price
    %th
    %th
    %th

  - @foods.each do |food|
    %tr
      %td= food.name
      %td= food.price
      %td= link_to 'Show', food
      %td= link_to 'Edit', edit_food_path(food)
      %td= link_to 'Destroy', food, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Food', new_food_path

app/views/foods/new.html.haml
%h1 New food

= render 'form'

= link_to 'Back', foods_path

app/views/foods/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @food.name
%p
  %b Price:
  = @food.price

= link_to 'Edit', edit_food_path(@food)
\|
= link_to 'Back', foods_path