config/routes.rb
EaLunchReservation::Application.routes.draw do
  root :to => "reservations#index"
  resources :reservations, except: :show do
    member do
      put :backup_availability
    end
  end
  resource :update, only: [:show]
  resources :foods, only: []
  resources :users, only: []
  resource :summaries, only: [] do
    get :today
    get :query
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "EA Lunch Reservation"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/favicon.ico" rel="shortcut icon")
  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
              %span.icon-bar
          = link_to 'EA Lunch Reservation', root_path, class: 'brand'
          .container.nav-collapse
            %ul.nav
              %li= link_to 'Reservations', reservations_path
              %li= link_to 'Today Summary', today_summaries_path
              %li= link_to 'Update food data', update_path
              - event = Event.last
              - if event
                %li= link_to "#{event.content} - #{event.created_at.in_time_zone.strftime('%k:%M %d/%m/%Y')}", '#'
              %li= link_to 'HanhThu - 3.5089063 - 3.6018457 - 0985807833', 'http://www.comhanhthu.com/'
    .container-fluid
      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Available foods
              - @foods.pluck(:name).each do |name|
                %li= name
        .span9
          - if controller_name == Reservation.table_name
            - if Time.zone.now > Reservation.deadline
              %h4 Reservation deadline (11:40AM) has been reached!
            - else
              %h1#countdown_timer{ style: 'height: 100px; padding-top: 15px; color: red;' }
          %br
          = bootstrap_flash
          = yield
      %footer
        %p &copy; Thach Chau 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    :javascript
      $(".chzn-select").chosen();
      $('#tabs').tab();
      if ($('#countdown_timer').length > 0){
        var deadline = new Date("#{Reservation.deadline.strftime('%B %e, %Y %H:%M:00')}")
        $('#countdown_timer').countdown({until: deadline, format: 'HMS'});
      }